export enum ScreenState {
  LOGIN = "LOGIN",
  REGISTER = "REGISTER",
  HOME = " ",
  CREATE_EVENT = "CREATE_EVENT",
  EVENTS = "EVENTS",
  EVENTS_LIST = "EVENTS_LIST",
  SUCCES_NOTIFICATION = "SUCCES_NOTIFICATION",
  BUY_TICKET = "BUY_TICKET",
  MY_EVENTS = "MY_EVENTS"
}
